services:
  postgres:
    image: postgres:16
    container_name: meu-postgres
    environment:
      POSTGRES_DB: usuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-identity
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - ./data/jaeger:/badger # Persistência relativa para os traces coletados

volumes:
  postgres_data: